services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: morning-chats-production
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - gibbs-apps
    volumes:
      # Persist session data and logs
      - ./memory:/usr/src/app/memory
      - ./logs:/usr/src/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "app=morning-chats"
      - "environment=production"

networks:
  gibbs-apps:
    external: true